# Generated by Django 4.0.2 on 2022-02-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('slug', models.CharField(max_length=225)),
                ('body', models.TextField()),
                ('images', models.ImageField(blank=True, default='Digital18.png', upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='posts', to='Boomie.Category')),
            ],
        ),
    ]
