# Generated by Django 4.0.2 on 2022-02-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boomie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Tijano', max_length=25),
        ),
    ]
