# Generated by Django 4.0.2 on 2022-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boomie', '0008_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.FilePathField(blank=True, default='Digital18.png', path='/images'),
        ),
    ]
