# Generated by Django 4.0.2 on 2022-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boomie', '0010_alter_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
