# Generated by Django 4.0.2 on 2022-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boomie', '0011_post_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default='Digital18.png', upload_to='media/'),
        ),
    ]
