# Generated by Django 4.0.2 on 2022-05-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_post_author_desc_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=225),
        ),
    ]
